---
# tasks file for hadoop
- name: downloading the file
  get_url:
    url: "{{ item }}"
    dest: /home/ec2-user/
  loop:
    - https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
    - https://lalitbucket6033.s3.ap-south-1.amazonaws.com/jdk-8u171-linux-x64.rpm 
- name: installing softwares
  command:
   cmd: "{{ item }}"
  args:
   warn: no
  loop:
    - rpm -ivh /home/ec2-user/jdk-8u171-linux-x64.rpm --force
    - rpm -ivh /home/ec2-user/hadoop-1.2.1-1.x86_64.rpm --force

- name: copying the core-site.xml
  template:
    src: ../templates/{{node_name}}/{{item}}
    dest: /etc/hadoop/{{item}}
  loop: 
    - core-site.xml
    - hdfs-site.xml

- name: creating direc
  file:
    path: "{{ direc_name }}"
    state: directory
    mode: '0755'

- name: formatting namenode
  shell: "echo Y|hadoop namenode -format"
  args:  
   warn: no
  when:
     node_name == "namenode"

- name: starting the services
  command: sudo hadoop-daemon.sh start "{{ node_name }}"
  args:  
   warn: no
  ignore_errors: yes
